# Generated by Django 2.0 on 2020-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empanelment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('serviceProviderCat', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('appointmentSchedule', models.DateField()),
                ('otherFacility', models.CharField(max_length=255)),
                ('isTransplant', models.BooleanField()),
                ('isEmergencyFacility', models.BooleanField()),
                ('isTraumaCare', models.BooleanField()),
                ('isBurnCase', models.BooleanField()),
                ('accre', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255, verbose_name='Near by Landmark')),
                ('doctorName', models.CharField(max_length=255)),
                ('doctorPhoto', models.ImageField(upload_to='images/')),
                ('profile', models.CharField(max_length=255)),
                ('serviceProviderPhoto', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
