# Generated by Django 2.0 on 2020-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropDown',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('serviceProviderCat', models.CharField(max_length=255)),
                ('accredition', models.CharField(max_length=255)),
            ],
        ),
    ]
