# Generated by Django 2.0 on 2020-02-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empanel', '0002_dropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdown',
            name='accredition',
        ),
        migrations.RemoveField(
            model_name='dropdown',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dropdown',
            name='serviceProviderCat',
        ),
        migrations.RemoveField(
            model_name='dropdown',
            name='state',
        ),
    ]
