# Generated by Django 2.0 on 2020-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empanel', '0003_auto_20200212_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accredition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accredition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceProviderCat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
    ]
