# Generated by Django 2.0 on 2020-02-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empanel', '0004_accredition_city_serviceprovider_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredition',
            name='accredition',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='country',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='serviceProviderCat',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
