# Generated by Django 2.0 on 2020-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empanel', '0005_auto_20200213_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAuthPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
