# Generated by Django 2.0 on 2020-02-13 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Empanel', '0006_addauthperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='empanelment',
            name='person',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
